### PR TITLE
Gh pages lev

### PR DESCRIPTION
**Pull request by dobiedad**

### CODE REVIEW

**Comment by refractalize** [comment]
wow, the spinny headers are a bit, um, spinny

**Comment by refractalize** [comment]
Also, skrollr stylesheets - I'm wondering if they impose a performance hit?

**Comment by joshski** [comment]
Yeah I think this page needs to get less mental, not more. Some scrolly plastiq examples would be great, but isolated to a small area of the page!

**Comment by leomdivani** [comment]
yeah im not sure, i just thought skrollr stylesheets was much cleaner than doing them inline

**Comment by joshski** [comment]
We gotta get rid of skrollr anyway

**Pull request closed without merging**
