### PR TITLE
Small addition to the docs on how to get started with development

### PR DESCRIPTION
**Pull request by Anchakor**

### CODE REVIEW

**Comment by refractalize** [comment]
@Anchakor that's ok, think I'll merge anyway and fix one or two things. cheers

**Comment by Anchakor** [comment]
@refractalize Cool, thanks.

**Comment by refractalize** [comment]
this is merged (rebased), see 69e777e863d4a26440d089dd64087b83732d8d9a

**Comment by refractalize** [comment]
thanks @Anchakor!

**Pull request closed without merging**
